version: '2'
services:
  dns:
    image: andyshinn/dnsmasq
    command: ["-d", "-q", "--log-facility=-"]
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_GENERATED_HOSTNAME: _{HOSTNAME_COMMAND}
      HOSTNAME_COMMAND: printf '%s_%s' kafka $$(docker inspect -f '{{index .Config.Labels "com.docker.compose.container-number"}}' $$HOSTNAME)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
