version: '3.7'

volumes:
  kafka:
  zookeeper:

services:
  zookeeper:
    image: wurstmeister/zookeeper
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 2181
        published: 2181
        mode: host
        protocol: tcp
    volumes:
    - zookeeper:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka:latest
    #hostname: '{{.Node.Hostname}}'
    deploy:
      replicas: 3
      #preferences:
      #  - spread: com.docker.swarm.node.id
    depends_on:
      - zookeeper
    ports:
      - target: 9094
        published: 9094
        mode: host
        protocol: tcp
    environment:
      #HOSTNAME_COMMAND: "hostname"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://{{.Node.Hostname}}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka:/kafka
